name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci2020:
    name: lint year 2020
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: year2020
  golangci2021:
    name: lint year 2021
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          working-directory: year2021
  gotest2020:
    name: test year 2020
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: year2020
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  gotest2021:
    name: test year 2021
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: year2021
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...


